[FEATURE] Add support for composer.json only extensions
The internal array always uses the extension key.
Not having an ext_emconf.php with dependencies to extension keys, but
only a composer.json with dependencies to package names will always
result in:

    UnexpectedValueException: The package "extension_key" depends on "composer/package-key" which is not present in the system.

This is a common situation in modern TYPO3 projects where multiple
extensions are given which declare their internal dependencies to have
proper TYPO3 loading order.

A fallback from the dependency (which might be the composer name) to the
actual extension key is added.

Resolves: #541